//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uShip.Logging
{


    public sealed class uShipLogging
    {

        private static uShipLoggingConfigurationSection _config;

        static uShipLogging()
        {
            _config = ((uShipLoggingConfigurationSection)(global::System.Configuration.ConfigurationManager.GetSection("uShip.Logging")));
        }

        private uShipLogging()
        {
        }

        public static uShipLoggingConfigurationSection Config
        {
            get
            {
                return _config;
            }
        }
    }

    public sealed partial class uShipLoggingConfigurationSection : System.Configuration.ConfigurationSection
    {

        [System.Configuration.ConfigurationPropertyAttribute("graphiteMetricPath", IsRequired = true)]
        public string GraphiteMetricPath
        {
            get
            {
                return ((string)(this["graphiteMetricPath"]));
            }
            set
            {
                this["graphiteMetricPath"] = value;
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("minimalDataLogMessage", IsRequired = true)]
        public string MinimalDataLogMessage
        {
            get
            {
                return ((string)(this["minimalDataLogMessage"]));
            }
            set
            {
                this["minimalDataLogMessage"] = value;
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("jsonReplacements")]
        [System.Configuration.ConfigurationCollectionAttribute(typeof(JsonReplacementsElementCollection.AddElement), AddItemName = "add")]
        public JsonReplacementsElementCollection JsonReplacements
        {
            get
            {
                return ((JsonReplacementsElementCollection)(this["jsonReplacements"]));
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("urlFormEncodedReplacements")]
        [System.Configuration.ConfigurationCollectionAttribute(typeof(UrlFormEncodedReplacementsElementCollection.AddElement), AddItemName = "add")]
        public UrlFormEncodedReplacementsElementCollection UrlFormEncodedReplacements
        {
            get
            {
                return ((UrlFormEncodedReplacementsElementCollection)(this["urlFormEncodedReplacements"]));
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("regexReplacements")]
        [System.Configuration.ConfigurationCollectionAttribute(typeof(RegexReplacementsElementCollection.AddElement), AddItemName = "add")]
        public RegexReplacementsElementCollection RegexReplacements
        {
            get
            {
                return ((RegexReplacementsElementCollection)(this["regexReplacements"]));
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("targetStackTraces")]
        [System.Configuration.ConfigurationCollectionAttribute(typeof(TargetStackTracesElementCollection.AddElement), AddItemName = "add")]
        public TargetStackTracesElementCollection TargetStackTraces
        {
            get
            {
                return ((TargetStackTracesElementCollection)(this["targetStackTraces"]));
            }
        }

        public sealed partial class JsonReplacementsElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public AddElement this[int i]
            {
                get
                {
                    return ((AddElement)(this.BaseGet(i)));
                }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new AddElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((AddElement)(element)).Field;
            }

            public sealed partial class AddElement : System.Configuration.ConfigurationElement
            {

                [System.Configuration.ConfigurationPropertyAttribute("field", IsRequired = true)]
                public string Field
                {
                    get
                    {
                        return ((string)(this["field"]));
                    }
                    set
                    {
                        this["field"] = value;
                    }
                }
            }
        }

        public sealed partial class UrlFormEncodedReplacementsElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public AddElement this[int i]
            {
                get
                {
                    return ((AddElement)(this.BaseGet(i)));
                }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new AddElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((AddElement)(element)).Field;
            }

            public sealed partial class AddElement : System.Configuration.ConfigurationElement
            {

                [System.Configuration.ConfigurationPropertyAttribute("field", IsRequired = true)]
                public string Field
                {
                    get
                    {
                        return ((string)(this["field"]));
                    }
                    set
                    {
                        this["field"] = value;
                    }
                }
            }
        }

        public sealed partial class RegexReplacementsElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public AddElement this[int i]
            {
                get
                {
                    return ((AddElement)(this.BaseGet(i)));
                }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new AddElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((AddElement)(element)).Field;
            }

            public sealed partial class AddElement : System.Configuration.ConfigurationElement
            {

                [System.Configuration.ConfigurationPropertyAttribute("field", IsRequired = true)]
                public string Field
                {
                    get
                    {
                        return ((string)(this["field"]));
                    }
                    set
                    {
                        this["field"] = value;
                    }
                }
            }
        }

        public sealed partial class TargetStackTracesElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public AddElement this[int i]
            {
                get
                {
                    return ((AddElement)(this.BaseGet(i)));
                }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new AddElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((AddElement)(element)).RootNamespace;
            }

            public sealed partial class AddElement : System.Configuration.ConfigurationElement
            {

                [System.Configuration.ConfigurationPropertyAttribute("rootNamespace", IsRequired = true)]
                public string RootNamespace
                {
                    get
                    {
                        return ((string)(this["rootNamespace"]));
                    }
                    set
                    {
                        this["rootNamespace"] = value;
                    }
                }
            }
        }
    }
}
